export const soundLibraryCategories = [
  "drums",
  "bass",
  "keys",
  "vocals",
  "fx",
  "loops",
] as const

export type SoundLibraryCategory = (typeof soundLibraryCategories)[number]

export type SoundLibraryItem = {
  id: string
  name: string
  category: SoundLibraryCategory
  role: string
  path: string
  license: string
  description: string
  bpm?: number
  key?: string
  tags: string[]
}

export const soundLibraryManifest: SoundLibraryItem[] = [
  {
    id: "proteverse-kick",
    name: "PRO-TEVERSE Kick",
    category: "drums",
    role: "kick",
    path: "/sound-library/drums/proteverse-kick.wav",
    license: "own-generated",
    description: "Synthetic starter kick generated by the PRO-TEVERSE sample script.",
    tags: ["kick", "drums", "amapiano", "starter"],
  },
  {
    id: "proteverse-clap",
    name: "PRO-TEVERSE Clap",
    category: "drums",
    role: "clap",
    path: "/sound-library/drums/proteverse-clap.wav",
    license: "own-generated",
    description: "Synthetic starter clap generated by the PRO-TEVERSE sample script.",
    tags: ["clap", "drums", "starter"],
  },
  {
    id: "proteverse-hat",
    name: "PRO-TEVERSE Hi-Hat",
    category: "drums",
    role: "hat",
    path: "/sound-library/drums/proteverse-hat.wav",
    license: "own-generated",
    description: "Synthetic starter hi-hat generated by the PRO-TEVERSE sample script.",
    tags: ["hat", "drums", "starter"],
  },
  {
    id: "proteverse-log-drum",
    name: "PRO-TEVERSE Log Drum",
    category: "bass",
    role: "bass",
    path: "/sound-library/bass/proteverse-log-drum.wav",
    license: "own-generated",
    description: "Synthetic starter log drum generated by the PRO-TEVERSE sample script.",
    tags: ["log drum", "bass", "amapiano", "starter"],
  },
  {
    id: "proteverse-chord-stab",
    name: "PRO-TEVERSE Chord Stab",
    category: "keys",
    role: "chord",
    path: "/sound-library/keys/proteverse-chord-stab.wav",
    license: "own-generated",
    description: "Synthetic starter chord stab generated by the PRO-TEVERSE sample script.",
    key: "C minor",
    tags: ["keys", "chord", "stab", "starter"],
  },
  {
    id: "proteverse-riser",
    name: "PRO-TEVERSE Riser",
    category: "fx",
    role: "fx",
    path: "/sound-library/fx/proteverse-riser.wav",
    license: "own-generated",
    description: "Synthetic starter riser generated by the PRO-TEVERSE sample script.",
    tags: ["fx", "riser", "transition", "starter"],
  },
]
